BEGIN;

CREATE SCHEMA IF NOT EXISTS ops_core;
CREATE SCHEMA IF NOT EXISTS ops_ai;
CREATE SCHEMA IF NOT EXISTS ops_rules;
CREATE SCHEMA IF NOT EXISTS ops_review;
CREATE SCHEMA IF NOT EXISTS ops_audit;

COMMIT;
