from __future__ import annotations

from collections.abc import Iterable
from typing import Protocol

from ops_agent.models import AuditEvent, CaseRecord, CaseResults, DocumentRecord, ReviewActionRecord, ReviewTaskRecord


class CaseRepository(Protocol):
    def save_case(self, case: CaseRecord) -> CaseRecord: ...
    def get_case(self, case_id: str) -> CaseRecord | None: ...


class DocumentRepository(Protocol):
    def save_document(self, document: DocumentRecord) -> DocumentRecord: ...
    def get_document(self, document_id: str) -> DocumentRecord | None: ...


class ReviewRepository(Protocol):
    def save_review_task(self, task: ReviewTaskRecord) -> ReviewTaskRecord: ...
    def get_review_task(self, task_id: str) -> ReviewTaskRecord | None: ...
    def list_review_tasks(self, *, status: str | None = None) -> list[ReviewTaskRecord]: ...
    def save_review_action(self, action: ReviewActionRecord) -> ReviewActionRecord: ...


class ResultsRepository(Protocol):
    def save_results(self, results: CaseResults) -> CaseResults: ...
    def get_results(self, case_id: str) -> CaseResults | None: ...


class AuditRepository(Protocol):
    def save_audit_event(self, event: AuditEvent) -> AuditEvent: ...
    def list_audit_events(self, case_id: str) -> Iterable[AuditEvent]: ...
